<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [1]:
import numpy as np

# convertimos la lista en array usando el método 'np.array()' 
array_unidimensional = np.arange(0,10)
print(f"El array unidimensional creado es: \n  {array_unidimensional} \n")

El array unidimensional creado es: 
  [0 1 2 3 4 5 6 7 8 9] 



#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [2]:
array_unidimensional = np.arange(1,11)
array_bidimensional = np.reshape(array_unidimensional,(2,5))
array_bidimensional

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [3]:
lista = [0,2,0,3,0,4,0]
array_unidimensional = np.array(lista)
print("All index value of 0 is: ", np.where(array_unidimensional == 0)[0]) # https://www.geeksforgeeks.org/how-to-find-the-index-of-value-in-numpy-array/

All index value of 0 is:  [0 2 4 6]


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [ ]:
array_randint_tri = np.random.random_sample((2, 3, 4))
print(np.arange(0,10))
array_randint_tri

array([[[0.90723542, 0.79761501, 0.53474207, 0.69853044],
        [0.37523249, 0.48486886, 0.0655753 , 0.77241318],
        [0.02818336, 0.91157202, 0.85638548, 0.61095495]],

       [[0.6649667 , 0.68153888, 0.10715556, 0.96533295],
        [0.41137554, 0.76572839, 0.80710228, 0.04207977],
        [0.12764263, 0.55549099, 0.4613364 , 0.49358695]]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [38]:
array_aleatorio = np.random.randint(0,100,(10))
f"The max value is {array_aleatorio.max()} and the min value is {array_aleatorio.min()}"

'The max value is 93 and the min value is 3'

#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:
array_aleatorio = np.random.randint(1,100,(10))
print(array_aleatorio)
print(np.invert(array_aleatorio))   #https://numpy.org/doc/stable/reference/generated/numpy.invert.html

[99 61 89 72 48 50 40 82  2 24]
[-100  -62  -90  -73  -49  -51  -41  -83   -3  -25]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [113]:
array_aleatdorio_3D = np.random.randint(1,24,(2,3,4))
print(array_aleatdorio_3D)

# Selecciona todos los elementos mayores que 15
mascara = array_aleatdorio_3D == 15 # mascara booleana
print(f"Primer 15: {array_aleatdorio_3D[mascara][0]}") # aplicamos mascara y mos quedamos con el primer 15

# selecciona todos los elementos del primer array. Usamos los indices,puesto que sabemos la estrucutra del array. El indice 0 es el primer array
print(f"Primer array: {array_aleatdorio_3D[0]}")

# Selecciona la ultima fila del ultimo array
print(f"Ultima final del ultimo array: {array_aleatdorio_3D[1,2]}")

[[[23 17  8 19]
  [11  5  7 16]
  [ 1 20  8  1]]

 [[ 5 13 14  4]
  [15 15  1 22]
  [ 2  5 21 17]]]
Primer 15: 15
Primer array: [[23 17  8 19]
 [11  5  7 16]
 [ 1 20  8  1]]
Ultima final del ultimo array: [ 2  5 21 17]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [ ]:
# Array 3D (3, 2, 5) con valores del 1 al 30
array_3d = np.arange(1, 31).reshape(3, 2, 5)
print(array_3d)
# Selecciona el subarray con los dos primeros elementos de cada fila de cada array

print(f"Subarray con los dos primeros elementos de cada fila de cada array:\n {array_3d[::,:2,:2]}")  # seleccionamos los dos arrays, los 2 primeros elementos de cada fila
print(f"Subarray todas filas ultimos arrays:\n {array_3d[1:,::,::]}") # contamos a partir del primer elemento y luego cogemos todos


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
Subarray con los dos primeros elementos de cada fila de cada array:
 [[[ 1  2]
  [ 6  7]]

 [[11 12]
  [16 17]]

 [[21 22]
  [26 27]]]
Subarray todas filas ultimos arrays:
 [[[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [161]:


array_3d = np.arange(1, 25).reshape(4,3,2)
print(array_3d)

# Cambia todos los elementos de la segunda fila del segundo array por 0
array_3d[1,1,::] = [0] ## https://www.geeksforgeeks.org/how-to-change-a-single-value-in-a-numpy-array/
print(array_3d)

# Cambia todos los elementos del ultimo array a -1
array_3d[3,::,::] = [-1]
print(array_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [ ]:
array_3d = np.arange(-10,14).reshape(2,4,3)
print(array_3d)

# selecciona todos los elementos mayores a 5
mascara = array_3d > 5 # mascara booleana
print(f"Elementos mayores a 5: {array_3d[mascara]}") # aplicamos mascara y mos quedamos con el primer 15

# Reemplazamos todos los elementos negativos por 0 ## https://www.projectpro.io/recipes/replace-items-that-satisfy-condition-with-another-value-numpy-array

condicion = (array_3d < 0) # define la condition, todos los valores menores que 0
nuevo_valor = 0 # nuevo valor
array_3d[condicion] = nuevo_valor # realiza el reemplazo
print(array_3d)



array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  1]],

       [[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]]])

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [ ]:
array_3d = np.arange(1, 28).reshape(3,3,3)
print(array_3d)

## Selecciona el subarray del segundo array que contenga solo las dos primeras columnas
mascara = array_3d > 5 # mascara booleana
print(f"Primer 15: {array_aleatdorio_3D[mascara][0]}") # aplicamos mascara y mos quedamos con el primer 15

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [190]:
array_aleatorio = np.random.randint(0,100,(10))
print(array_aleatorio)

## reemplazar valores 
maximo = np.max(array_aleatorio)
minimo = np.min(array_aleatorio)

# reemplaza max
condicion = (array_aleatorio == maximo) # define la condition
nuevo_valor = 0 # nuevo valor
array_aleatorio[condicion] = nuevo_valor # realiza el reemplazo

# reemplaza min
condicion = (array_aleatorio == minimo) # define la condition
nuevo_valor = 0 # nuevo valor
array_aleatorio[condicion] = nuevo_valor # realiza el reemplazo

print(array_aleatorio)

[48 38 27 50 67 80 48 56 24 86]
[48 38 27 50 67 80 48 56  0  0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [192]:
array_aleatorio = np.random.randint(1,100,(15))
print(array_aleatorio)

ordenadito = np.sort(array_aleatorio)
print(ordenadito)




[10 34 65 10  5 88 91 88 14  4 35 38 83 47 50]
[ 4  5 10 10 14 34 35 38 47 50 65 83 88 88 91]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [ ]:
array_2D = np.random.randint(1,100,(4,4))
print(array_2D)
#Columnas
suma0 = np.sum(array_2D, axis=0)
print(suma0)
#Filas
suma1 = np.sum(array_2D, axis=1)
print(suma1)

[[80 37  7 59]
 [27 33 59 99]
 [20 41 60 15]
 [56 16 19 19]]
[183 127 145 192]
[183 218 136 110]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [ ]:
array_2D = np.zeros((5,5))
valor = 1 #valor a reemplazar
array_2D[0, :] = valor # fila 1
array_2D[4, :] = valor  # fila 5
array_2D[:, 0] = valor  # columna 1
array_2D[:, 4] = valor  # columna 5

array_2D




array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [208]:
array_2D = np.random.randint(1,10,(4,4))
media = np.mean(array_2D)
devstd = np.std(array_2D)

print(f"La media es {media} y la desviacione standar es {devstd}")



La media es 6.3125 y la desviacione standar es 1.9273929931386593


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [ ]:
array_3d = np.arange(1, 25).reshape(2, 3, 4)

array_transpuesto = np.transpose(array_3d, (2, 1, 0))

print("Array original (2, 3, 4):")
print(array_3d)

print("\nArray transpuesto (4, 3, 2):")
print(array_transpuesto)

Array original (2, 3, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Array transpuesto (4, 3, 2):
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


Con 4,3,2 lo que queremos hacer es pasar de un array de 2 arrays, 3 filas y 4 columnas a uno de 4 arrays de 3 filas cada uno y 2 columnas.

- EL numero de arrays pasa a sar el numero de columnas. 
- El numero de filas se mantiene.
- El numero columnas pasa a ser el numero de arrays. 

En este caso definimos el order que queremos de salida (2,1,0)

```python
np.transpose(multidimensional, (2,1,0))
```

Si nos fijamos lo que hacemos en la tupla es, basándonos en las posiciones de la tupla:

- ¿Qué quiero en la posición 0 de la tupla (y por lo tanto de mi nuevo *array* transpuesto*? -- > lo que antes era la posición 2. Por lo tanto, pongo un 2


- ¿Qué quiero en la posción 1? --> lo que antes era la posición 1. Por lo tanto, pongo un 1



- ¿Qué quiero en la posición 2? --> lo que antes era la posición 0. Por lo tanto, pongo un 0

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [232]:
array_3d = np.arange(1, 25).reshape(3,4,2)

array_transpuesto = np.transpose(array_3d, (1,0,2))

print("Array original (3, 4, 2):")
print(array_3d)

print("\nArray transpuesto (4, 3, 2):")
print(array_transpuesto)

Array original (3, 4, 2):
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]

Array transpuesto (4, 3, 2):
[[[ 1  2]
  [ 9 10]
  [17 18]]

 [[ 3  4]
  [11 12]
  [19 20]]

 [[ 5  6]
  [13 14]
  [21 22]]

 [[ 7  8]
  [15 16]
  [23 24]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [239]:
array_3d = np.arange(1, 25).reshape(3,2,4)
print(array_3d)
array_transpose = array_3d.transpose()
array_transpose

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


array([[[ 1,  9, 17],
        [ 5, 13, 21]],

       [[ 2, 10, 18],
        [ 6, 14, 22]],

       [[ 3, 11, 19],
        [ 7, 15, 23]],

       [[ 4, 12, 20],
        [ 8, 16, 24]]])

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [ ]:
import numpy as np
# Array 3D 
array_3D = np.random.randint(-10,10,(3,4,5))
print(array_3D)

print("\n------EMPTY ARRAY------\n")

# Array Empty 
array_empty = np.empty((3,4,5))

print(array_empty)

# Si valor igual a la mediana, se reemplaza por M
print("\n------Si valor igual a la mediana, se reemplaza por M------\n")
mediana = np.mean(array_empty)
print(mediana)
condicion = (array_empty == mediana) # define la condition
nuevo_valor = 'M' # nuevo valor
array_empty[condicion] = nuevo_valor # realiza el reemplazo
array_empty

##!!!!! No entinedo este ejercicio, por que pide reemplzar valores con letras en un array???

# Si valor mayor a la mediana, se reemplaza por X

# Si valor menor a la mediana, se reemplaza por Y

# Si valor igual al Maximo, se reemplaza por MAX

# Si valor igual al Minimo, se reemplaza por MIN


[[[  0  -3  -8  -3   0]
  [  6  -3   2  -1  -3]
  [  0   9   0  -5  -4]
  [ -3  -6   8   1  -9]]

 [[ -9   8   0   4 -10]
  [ -2  -8   7  -2   1]
  [  5  -3   1   8   0]
  [  4  -4   0  -6   5]]

 [[  7  -9   2   9  -2]
  [ -4   7   9  -5  -9]
  [ -1  -2  -7   1  -3]
  [  7   9   9  -3  -4]]]

------EMPTY ARRAY------

[[[ 1.08703609e-311  1.08701884e-311  2.33419537e-312  0.00000000e+000
    1.39067116e-309]
  [ 8.69169479e-311  2.14745974e-311  1.69760311e-313  0.00000000e+000
    0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  1.55367112e+030
   -3.72620332e-212]
  [ 1.67637668e-312  5.01402526e+180  5.15723648e-062  2.86523877e+161
    2.42847723e+098]]

 [[ 4.81778088e+209  3.55152101e+180  5.73116149e-322  0.00000000e+000
    0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
    0.00000000e+000]
  [ 4.94065646e-324  0.00000000e+000  0.00000000e+000  0.00000000e+000
    0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+0

ValueError: could not convert string to float: 'M'

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [84]:
array_bi = np.random.randint(1,3,(4,4))  ## hacemos un sencillito para que tenga chicha
print(array_bi)
print("\n----------Lista de Filas--------\n")

lista_de_filas = [] ## https://www.geeksforgeeks.org/python-convert-array-ordinary-list-items/

for element in array_bi:
    lista_de_filas.append(list(element)) # para convertirlo a lista

print(lista_de_filas)

print("\n----------Lista de columnas--------\n")
lista_de_columnas = []

for element in np.transpose(array_bi):
    lista_de_columnas.append(list(element)) # para convertirlo a lista

print(lista_de_columnas)

for filas in lista_de_filas:
    if filas in lista_de_columnas:
        print(f"\nLa fila {filas} esta presente en alguna columna")
    else:
        print(f"\nNo hay filas repetidas")

[[1 1 2 1]
 [1 2 1 2]
 [1 1 1 2]
 [2 2 1 2]]

----------Lista de Filas--------

[[1, 1, 2, 1], [1, 2, 1, 2], [1, 1, 1, 2], [2, 2, 1, 2]]

----------Lista de columnas--------

[[1, 1, 1, 2], [1, 2, 1, 2], [2, 1, 1, 1], [1, 2, 2, 2]]

No hay filas repetidas

La fila [1, 2, 1, 2] esta presente en alguna columna

La fila [1, 1, 1, 2] esta presente en alguna columna

No hay filas repetidas
